### ISSUE TITLE
Fatal error after clean install 

### ISSUE THREAD

**Issue by yairpe** [cardinity/cardinity-example-php#7]
Installed as described.
Selected Create New Payment and clicked Pay

Received a stack dump:
`
Fatal error: Uncaught TypeError: Argument 1 passed to Cardinity\Method\ResultObjectMapper::map() must be of the type array, null given, called in C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Http\Guzzle\ExceptionMapper.php on line 84 and defined in C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Method\ResultObjectMapper.php:38 Stack trace: #0 C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Http\Guzzle\ExceptionMapper.php(84): Cardinity\Method\ResultObjectMapper->map(NULL, Object(Cardinity\Method\Error)) #1 C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Http\Guzzle\ExceptionMapper.php(34): Cardinity\Http\Guzzle\ExceptionMapper->create('Cardinity\\Excep...', Object(GuzzleHttp\Exception\ClientException), Object(Cardinity\Method\Payment\Create)) #2 C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Http\Guzzle\ClientAdapter.php(53): Cardinity\Http\Guzzle\ExceptionMapper->get(Object(GuzzleHttp\Exceptio in C:\Apache24\htdocs\test\cardinity\vendor\cardinity\cardinity-sdk-php\src\Method\ResultObjectMapper.php on line 38
`

**Comment by shababcardinity** [comment]
Can you share your php version, Was the .env file configured correctly?

**Comment by shababcardinity** [comment]
You are probably using from a localhost. Requests from localhost or 127.0.0.1 is rejected by the server. 
In case of a local development environment you have these options -
1) use your computer IP address instead. 
2) use something like ngrok
3) or have a development url using etc/hosts.

**Comment by yairpe** [comment]
after updating code and composer and following the instructions, I get an error

Fatal error: Uncaught Error: Class 'Router' not found in C:\Apache24\htdocs\apps\spilnew\public_html\test\cardinity\cardinity-example-php-master\public\index.php:20 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\apps\spilnew\public_html\test\cardinity\cardinity-example-php-master\public\index.php on line 20

(.env file has the correct values. php 7.4)

seems like a namespace issue.
